name: my_game
description: An absolute bare-bones web app.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^3.0.0

scripts:
  start: "webdev serve"
  build: 'cd web && dart compile js main.dart -o main.dart.js && del "main.dart.js.deps" "main.dart.js.map"'
