name: Dart Tests

on:
  push:
    branches:
      - main # Adjust the branch as needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1.6.2
        with:
          sdk: "stable"

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: rps test # Modify this line to run your specific test command
